openapi: 3.0.0
paths:
  /api/app/api-check:
    get:
      operationId: AppController_getHello
      summary: protected by api-key guard
      parameters: []
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: string
      tags: &ref_0
        - app
      security:
        - apiKey: []
  /api/app/statistics/api-key:
    get:
      operationId: AppController_getApiKeyStatistics
      parameters: []
      responses:
        "200":
          description: ""
      tags: *ref_0
  /api/stadiums:
    get:
      operationId: StadiumsController_getMany
      summary: protected by firbease-JWT
      parameters: []
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/StadiumItem"
      tags: &ref_1
        - stadiums
      security: &ref_2
        - bearer: []
  /api/stadiums/{id}:
    get:
      operationId: StadiumsController_getOne
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StadiumItem"
      tags: *ref_1
      security: *ref_2
    put:
      operationId: StadiumsController_update
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateStadiumDto"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StadiumItem"
      tags: *ref_1
      security: *ref_2
  /api/teams:
    get:
      operationId: TeamsController_getMany
      summary: protected by firbease-JWT
      parameters: []
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
      tags: &ref_3
        - teams
      security: &ref_4
        - bearer: []
    post:
      operationId: TeamsController_create
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateTeamDto"
      responses:
        "201":
          description: ""
          content:
            application/json:
              schema:
                type: object
      tags: *ref_3
      security: *ref_4
  /api/teams/{id}:
    get:
      operationId: TeamsController_getOne
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: object
      tags: *ref_3
      security: *ref_4
    put:
      operationId: TeamsController_update
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateTeamDto"
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: object
      tags: *ref_3
      security: *ref_4
    delete:
      operationId: TeamsController_delete
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        "200":
          description: ""
      tags: *ref_3
      security: *ref_4
  /api/teams/{id}/image:
    post:
      operationId: TeamsController_uploadImage
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        "201":
          description: ""
          content:
            application/json:
              schema:
                type: string
      tags: *ref_3
      security: *ref_4
  /api/teams/{id}/imageUrl:
    get:
      operationId: TeamsController_getUrlImage
      parameters:
        - name: id
          required: true
          in: path
          schema:
            type: string
      responses:
        "200":
          description: ""
      tags: *ref_3
      security: *ref_4
  /api/auth/register:
    post:
      operationId: AuthController_signUp
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/RegisterDto"
      responses:
        "201":
          description: ""
          content:
            application/json:
              schema:
                type: object
      tags: &ref_5
        - auth
  /api/auth/forgot-password:
    post:
      operationId: AuthController_forgotPassword
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ForgotPasswordDto"
      responses:
        "200":
          description: ""
      tags: *ref_5
  /api/auth/login:
    post:
      operationId: AuthController_login
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/LoginDto"
      responses:
        "200":
          description: ""
      tags: *ref_5
  /api/auth/change-password:
    post:
      operationId: AuthController_changePassword
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/ChangePasswordDto"
      responses:
        "201":
          description: ""
      tags: *ref_5
      security:
        - bearer: []
info:
  title: Football Finder
  description: Football Finder - API - development
  version: "1.0"
  contact: {}
tags: []
servers: []
components:
  securitySchemes:
    bearer:
      scheme: bearer
      bearerFormat: JWT
      type: http
    apiKey:
      type: apiKey
      in: header
      name: X-API-KEY
  schemas:
    StadiumItem:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        latitude:
          type: number
        longitude:
          type: number
        description:
          type: string
        createdAt:
          format: date-time
          type: string
        updatedAt:
          format: date-time
          type: string
        teamId:
          type: string
      required:
        - id
        - name
        - latitude
        - longitude
        - description
        - createdAt
        - updatedAt
        - teamId
    UpdateStadiumDto:
      type: object
      properties:
        name:
          type: string
        latitude:
          type: number
        longitude:
          type: number
        description:
          type: string
          nullable: true
      required:
        - name
        - latitude
        - longitude
        - description
    CreateTeamDto:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
      required:
        - name
    UpdateTeamDto:
      type: object
      properties:
        name:
          type: string
        description:
          type: string
      required:
        - name
    RegisterDto:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
        firstName:
          type: string
        lastName:
          type: string
      required:
        - email
        - password
        - firstName
        - lastName
    ForgotPasswordDto:
      type: object
      properties:
        email:
          type: string
      required:
        - email
    LoginDto:
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      required:
        - email
        - password
    ChangePasswordDto:
      type: object
      properties:
        password:
          type: string
      required:
        - password
